version: "3"
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3050:8080"

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - UNO=uno
      - DOS=dos
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

volumes:
  data:
